# permissions for end users to edit fdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: f-operator2
    app.kubernetes.io/part-of: f-operator2
    app.kubernetes.io/managed-by: kustomize
  name: fdeployment-editor-role
rules:
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdeployments/status
  verbs:
  - get
