# permissions for end users to edit fdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fdatabase-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: f-operator
    app.kubernetes.io/part-of: f-operator
    app.kubernetes.io/managed-by: kustomize
  name: fdatabase-editor-role
rules:
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases/status
  verbs:
  - get
