---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - serviceaccounts
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases
  - fdeployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases/finalizers
  - fdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases/status
  - fdeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - delete
  - get
  - list
  - watch
