---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases/finalizers
  verbs:
  - update
- apiGroups:
  - k8s.fabkli.ch
  resources:
  - fdatabases/status
  verbs:
  - get
  - patch
  - update
