apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  name: fdeployment-sample
spec:
  path: "/"
  replicas: 2
  port: 8080
  tag: "latest"
  image: "test-image" # ghcr.io/fabiokaelin/test-image:latest
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  healthCheck:
    livenessProbe:
      path: "/"
    readinessProbe:
      path: "/"
  host: "env.fabkli.ch"
  env:
    - name: FOO
      value: foo-value
    - name: BAR
      fromConfig:
        name: environment-test
        key: BAR
    - name: BAZ
      fromSecret:
        name: environment-test
        key: BAZ