apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  name: testapplication-backend
spec:
  path: "/"
  replicas: 1
  port: 8080
  tag: "1.0.0"
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 128Mi
  healthCheck:
    livenessProbe:
      path: "/"
    readinessProbe:
      path: "/"
  host: "testapplication.fabkli.ch"
  database: "testapplication"
  env:
    - name: TEST_ENV_1
      value: test-value
    - name: DB_PASSWORD
      database: "testapplication"
      # secretRef: testapplication-db-password