apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  labels:
    app.kubernetes.io/name: fdeployment
    app.kubernetes.io/instance: fdeployment-sample
    app.kubernetes.io/part-of: f-operator2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: f-operator2
  name: fdeployment-sample
spec:
  # TODO(user): Add fields here
  component: main
  app: testapplication
  path: "/api"
  replicas: 1
  port: 8080