apiVersion: k8s.fabkli.ch/v1
kind: Fdeployment
metadata:
  name: testapplication-backend
spec:
  path: "/"
  replicas: 1
  port: 8080
  resources:
    requests: # minimum (ensured)
      memory: "128Mi"
      cpu: "50m"
    limits: # maximum (allowed)
      memory: "1024Mi"
      cpu: "200m"