apiVersion: k8s.fabkli.ch/v1
kind: Fdatabase
metadata:
  name: fdatabase-sample
spec:
  rootHost: "localhost" # optional
  database:
    value: "tipp"
  user:
    value: "usertipp"
  rootPassword:
    fromSecret:
      name: dev-secrets
      key: DATABASE_ROOT_PASSWORD
  password:
    fromSecret:
      name: dev-secrets
      key: DATABASE_PASSWORD
