apiVersion: k8s.fabkli.ch/v1
kind: Fdatabase
metadata:
  name: fdatabase-sample
spec:
  database: "tipp"
  rootHost: "%" # optional
  user: "usertipp"
  rootPassword:
    fromSecret:
      name: dev-secrets
      key: DATABASE_ROOT_PASSWORD
  password:
    fromSecret:
      name: dev-secrets
      key: DATABASE_PASSWORD
