apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-14T13:34:49Z"
  generation: 1
  name: testapplication-backend
  namespace: ivp-foperator
  ownerReferences:
  - apiVersion: k8s.fabkli.ch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Fdeployment
    name: testapplication-backend
    uid: 22fc23a5-d2ef-441d-a358-6b7b4777f371
  resourceVersion: "4179404"
  uid: f2986aa5-b53c-4ed5-9dec-103afeab6b4b
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: testapplication-backend
      app.kubernetes.io/version: ""
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: testapplication-backend
        app.kubernetes.io/version: ""
    spec:
      automountServiceAccountToken: false
      containers:
      - image: ghcr.io/fabiokaelin/testapplication-backend:1.0.0
        imagePullPolicy: IfNotPresent
        name: testapplication-backend
        ports:
        - containerPort: 8080
          name: containerport
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
status:
  conditions:
  - lastTransitionTime: "2023-06-14T13:34:49Z"
    lastUpdateTime: "2023-06-14T13:34:49Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-06-14T13:34:49Z"
    lastUpdateTime: "2023-06-14T13:34:49Z"
    message: ReplicaSet "testapplication-backend-69c88c89ff" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
