apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-06-14T13:02:04Z"
  generation: 1
  name: testapplication-backend
  namespace: ivp-foperator
  ownerReferences:
  - apiVersion: k8s.fabkli.ch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Fdeployment
    name: testapplication-backend
    uid: ba0128ac-3785-475a-90da-cce811dd5909
  resourceVersion: "4167101"
  uid: 95647d0c-c6d4-41d5-ad41-85a5e52d0898
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: testapplication-backend
      app.kubernetes.io/version: ""
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: testapplication-backend
        app.kubernetes.io/version: ""
    spec:
      containers:
      - image: ghcr.io/fabiokaelin/testapplication-backend
        imagePullPolicy: Always
        name: testapplication-backend
        ports:
        - containerPort: 8080
          name: containerport
          protocol: TCP
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-14T13:02:07Z"
    lastUpdateTime: "2023-06-14T13:02:07Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-14T13:02:04Z"
    lastUpdateTime: "2023-06-14T13:02:07Z"
    message: ReplicaSet "testapplication-backend-5595b54859" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
