name: Continuous Deployment


on:
  # schedule:
    # - cron: '25 19 * * *'
  push:
    branches:
    - "main"
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

# env:
  # REGISTRY: ghcr.io


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: login ghcr.io
        run: |
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}

      - name: build and push
        run: |
          make docker-buildx

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
        id: install

      - name: set kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "apiVersion: v1" > ~/.kube/config
          echo "clusters:" >> ~/.kube/config
          echo "- cluster:" >> ~/.kube/config
          echo "    extensions:" >> ~/.kube/config
          echo "    - extension:" >> ~/.kube/config
          echo "        last-update: Thu, 22 Jun 2023 19:21:36 CEST" >> ~/.kube/config
          echo "        provider: minikube.sigs.k8s.io" >> ~/.kube/config
          echo "        version: v1.30.1" >> ~/.kube/config
          echo "      name: cluster_info" >> ~/.kube/config
          echo "    server: https://k8s.fabkli.ch" >> ~/.kube/config
          echo "  name: minikube" >> ~/.kube/config
          echo "contexts:" >> ~/.kube/config
          echo "- context:" >> ~/.kube/config
          echo "    cluster: minikube" >> ~/.kube/config
          echo "    extensions:" >> ~/.kube/config
          echo "    - extension:" >> ~/.kube/config
          echo "        last-update: Thu, 22 Jun 2023 19:21:36 CEST" >> ~/.kube/config
          echo "        provider: minikube.sigs.k8s.io" >> ~/.kube/config
          echo "        version: v1.30.1" >> ~/.kube/config
          echo "      name: context_info" >> ~/.kube/config
          echo "    namespace: test" >> ~/.kube/config
          echo "    user: minikube" >> ~/.kube/config
          echo "  name: minikube" >> ~/.kube/config
          echo "current-context: minikube" >> ~/.kube/config
          echo "kind: Config" >> ~/.kube/config
          echo "preferences: {}" >> ~/.kube/config
          echo "users:" >> ~/.kube/config
          echo "- name: minikube" >> ~/.kube/config
          echo "  user:" >> ~/.kube/config
          echo "    password: ${KUBE_PWD}" >> ~/.kube/config
          echo "    username: minikube" >> ~/.kube/config
        env:
          KUBE_PWD: ${{ secrets.KUBE_PWD }}

      - name: deploy
        run: |
          make kustomize
          make undeploy ignore-not-found=true | true
          make deploy
